server:
  port: 8081

concertticket:
  server:
    url: http://localhost:8080

redis:
  host: 127.0.0.1
  port: 6379


logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG

